### ISSUE TITLE
Replication fails if filtered tables are not in public schema

### ISSUE THREAD

**Issue by skeggr** [xataio/pgstream#437]
### Summary

When running `pgstream run` with table filtering in the configuration file, and the filter contains tables that are not in the `public` schema, the application exits with code 1 and the following error:
```
Error: error running pg_dump: exit status 1: pg_dump: error: no matching tables were found
```
This occurs when using the "schemaname.tablename" format in the config file, as described in the documentation.

### Relevant Information

pgstream version: 0.7.3

### Steps to reproduce

1. Create a database.
2. Create any schema and any table within it.
3. Create a configuration file (`config.yaml`). Here is an example using custom database, schema, and table names:
    ```
    source:
      postgres:
        url: "postgresql://postgres:postgres@localhost:5432/simple_inventory_db?sslmode=disable"
        mode: snapshot_and_replication # options are replication, snapshot or snapshot_and_replication
        replication:
          replication_slot: pgstream_slot
        snapshot: # when mode is snapshot or snapshot_and_replication
          mode: full # options are data_and, schema or data
          tables:
            - "inventory.categories"
          recorder:
            repeatable_snapshots: true # whether to repeat snapshots that have already been taken
            postgres_url: "postgresql://postgres:postgres@localhost:5432/simple_inventory_db?sslmode=disable" # URL of the database where the snapshot status is recorded
          snapshot_workers: 4 # number of schemas to be snapshotted in parallel
          data: # when mode is full or data
            schema_workers: 4 # number of schema tables to be snapshotted in parallel
            table_workers: 4 # number of workers to snapshot a table in parallel
            batch_bytes: 83886080 # bytes to read per batch (defaults to 80MiB)
          schema: # when mode is full or schema
            mode: pgdump_pgrestore # options are pgdump_pgrestore or schemalog
            pgdump_pgrestore:
              clean_target_db: false # whether to clean the target database before restoring
    
    target:
      postgres:
        url: "postgresql://postgres:postgres@localhost:5999/simple_inventory_db?sslmode=disable"
        batch:
          timeout: 5000 # batch timeout in milliseconds
          size: 25 # number of messages in a batch
        disable_triggers: true # whether to disable triggers on the target database
        on_conflict_action: "nothing" # options are update, nothing or error
    
    modifiers:
      filter: # one of include_tables or exclude_tables
        include_tables: # list of tables for which events should be allowed. Tables should be schema qualified. If no schema is provided, the public schema will be assumed. Wildcards "*" are supported.
          - "inventory.categories"
    ```
4. Execute pgstream:
    ```
    pgstream init -c config.yaml && \
    pgstream run -c config.yaml --log-level trace
    ```

The application exits with code 1 and logs:

```
2025-07-11T16:20:59.272690987Z INF logger.go:37 > postgres processor configured
2025-07-11T16:20:59.273137638Z INF logger.go:37 > adding filtering to processor...
2025-07-11T16:20:59.273224966Z INF logger.go:37 > postgres listener configured
2025-07-11T16:20:59.273372337Z INF logger.go:37 > initial snapshot enabled
2025-07-11T16:20:59.273436991Z INF logger.go:37 > postgres processor configured
2025-07-11T16:20:59.273499584Z INF logger.go:37 > postgres bulk ingest writer enabled
2025-07-11T16:20:59.273734699Z INF logger.go:37 > adding filtering to processor...
2025-07-11T16:20:59.321770365Z INF logger.go:37 > starting listener...
2025-07-11T16:20:59.349239843Z INF logger.go:37 > creating schema snapshot module=postgres_schema_snapshot_generator schemaTables={"inventory":["categories"]}
2025-07-11T16:20:59.578579206Z ERR logger.go:45 > creating snapshot error.message="error running pg_dump: exit status 1: pg_dump: error: no matching tables were found\n" module=snapshot_generator_adapter schemas=["inventory"] tables=[]
2025-07-11T16:20:59.578739461Z INF logger.go:37 > snapshot generation completed duration=237.411795ms err={} module=snapshot_generator_adapter
2025-07-11T16:20:59.578893154Z ERR logger.go:45 > pg snapshot and listen error.message="error running pg_dump: exit status 1: pg_dump: error: no matching tables were found\n" module=wal_postgres_listener
2025-07-11T16:20:59.579028251Z INF logger.go:37 > stopping listener...
2025-07-11T16:20:59.579113861Z INF logger.go:37 > closing snapshot generator module=snapshot_generator_adapter
2025-07-11T16:20:59.579140411Z DBG logger.go:33 > context terminated, draining in flight batch module=postgres_batch_writer
2025-07-11T16:20:59.57945519Z DBG logger.go:33 > closing bulk ingest writer module=postgres_bulk_ingest_writer
2025-07-11T16:20:59.579545705Z DBG logger.go:33 > closing batch writer module=postgres_batch_writer
2025-07-11T16:20:59.57960338Z TRC logger.go:29 > closing batch sender module=postgres_batch_writer
2025-07-11T16:20:59.57965583Z TRC logger.go:29 > batch sender closed module=postgres_batch_writer
Error: error running pg_dump: exit status 1: pg_dump: error: no matching tables were found
```
No errors occur if the `public` schema is used.

**Comment by skeggr** [comment]
Hello @gulcin,
Thank you for the reply.
Yes, `pg_dump` works with the same credentials.
And what's more - pgstream works in `mode: replication`. Config:
```
source:
  postgres:
    url: "postgresql://postgres:postgres@localhost:5432/simple_inventory_db?sslmode=disable"
    mode: replication # options are replication, snapshot or snapshot_and_replication
    replication:
      replication_slot: pgstream_slot

target:
  postgres:
    url: "postgresql://postgres:postgres@localhost:5999/simple_inventory_db?sslmode=disable"
    batch:
      timeout: 5000 # batch timeout in milliseconds
      size: 25 # number of messages in a batch
    disable_triggers: true # whether to disable triggers on the target database
    on_conflict_action: "nothing" # options are update, nothing or error

modifiers:
  filter: # one of include_tables or exclude_tables
    include_tables: # list of tables for which events should be allowed. Tables should be schema qualified. If no schema is provided, the public schema will be assumed. Wildcards "*" are supported.
      - "inventory.categories"
```
Let's run pgstream and add a record to the `inventory.categories` table in the source database:

```
pgstream run -c config.yaml --log-level trace
using config file: config.yaml
2025-07-14T16:11:16.596350216Z INF logger.go:37 > postgres processor configured
2025-07-14T16:11:16.597017961Z INF logger.go:37 > adding filtering to processor...
2025-07-14T16:11:16.597100722Z INF logger.go:37 > postgres listener configured
2025-07-14T16:11:16.59717368Z INF logger.go:37 > starting listener...
2025-07-14T16:11:16.614379173Z TRC logger.go:29 > read last LSN position db_name=simple_inventory_db module=postgres_replication_handler position=28C/F40DB750 slot_name=pgstream_slot system_id=7480911317629857806
2025-07-14T16:11:16.614528783Z TRC logger.go:29 > set start LSN db_name=simple_inventory_db module=postgres_replication_handler position=28C/F40DB750 slot_name=pgstream_slot system_id=7480911317629857806
2025-07-14T16:11:16.616357072Z INF logger.go:37 > logical replication started db_name=simple_inventory_db module=postgres_replication_handler position=2804413241832 slot_name=pgstream_slot system_id=7480911317629857806
2025-07-14T16:11:16.616573838Z TRC logger.go:29 > stored new LSN position module=postgres_replication_handler position=28C/F40DB750
2025-07-14T16:11:16.616843491Z TRC logger.go:29 > module=wal_postgres_listener server_time=2025-07-14T16:11:16.616069Z wal_data= wal_end=28C/F40DB750
< skipped some trace messages >
2025-07-14T16:11:28.607918343Z TRC logger.go:29 > module=wal_postgres_listener server_time=2025-07-14T16:11:28.607451Z wal_data= wal_end=28C/F40E4AE0
2025-07-14T16:11:28.61112936Z TRC logger.go:29 > module=wal_postgres_listener server_time=2025-07-14T16:11:28.610667Z wal_data="{\"action\":\"I\",\"timestamp\":\"2025-07-14 16:11:28.606286+00\",\"lsn\":\"28C/F40E4B48\",\"schema\":\"inventory\",\"table\":\"categories\",\"columns\":[{\"name\":\"category_id\",\"type\":\"integer\",\"value\":11},{\"name\":\"category_name\",\"type\":\"character varying(50)\",\"value\":\"Smart Home\"},{\"name\":\"description\",\"type\":\"text\",\"value\":\"Products for home automation and smart living\"},{\"name\":\"created_at\",\"type\":\"timestamp without time zone\",\"value\":\"2025-07-14 16:11:28.603402\"},{\"name\":\"active\",\"type\":\"boolean\",\"value\":true}]}" wal_end=28C/F40E4D3A
2025-07-14T16:11:28.650022732Z DBG logger.go:33 > batching query args=[11,"Smart Home","Products for home automation and smart living","2025-07-14 16:11:28.603402",true] commit_position=28C/F40E4D3A module=postgres_batch_writer sql="INSERT INTO \"inventory\".\"categories\"(\"category_id\", \"category_name\", \"description\", \"created_at\", \"active\") OVERRIDING SYSTEM VALUE VALUES($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING"
2025-07-14T16:11:28.650206085Z TRC logger.go:29 > module=wal_postgres_listener server_time=2025-07-14T16:11:28.610851Z wal_data= wal_end=28C/F40E5168
2025-07-14T16:11:31.600242516Z DBG logger.go:33 > sending batch batch_size=1 module=postgres_batch_writer
2025-07-14T16:11:31.629816251Z TRC logger.go:29 > stored new LSN position module=postgres_replication_handler position=28C/F40E4D3A
2025-07-14T16:11:31.635819736Z TRC logger.go:29 > module=wal_postgres_listener server_time=2025-07-14T16:11:31.635442Z wal_data= wal_end=28C/F40E5168
```

Check the destination DB:

```
simple_inventory_db=> select * from inventory.categories where category_id=11;
 category_id | category_name |                  description                  |         created_at         | active
-------------+---------------+-----------------------------------------------+----------------------------+--------
          11 | Smart Home    | Products for home automation and smart living | 2025-07-14 16:11:28.603402 | t
(1 row)
```

As you mentioned earlier, the bug may be related to how pgstream interacts with pg_dump in `snapshot` and `snapshot_and_replication` modes.

**Comment by gulcin** [comment]
Hello @skeggr we're trying to reproduce this issue and will keep you updated.

**Comment by gulcin** [comment]
Hello @skeggr we've just published a bugfix [release](https://github.com/xataio/pgstream/releases/tag/v0.7.5) which includes a [fix](https://github.com/xataio/pgstream/pull/441) for the problem you encountered. Let us know if it resolves your issue. Thanks!

**Comment by skeggr** [comment]
Hello @gulcin,

Thank you, it now works well in pgstream v0.7.5.

P.S. I still have a few questions that I couldn't find answers to when using pgstream with a larger database. Could you clarify:
1. How can I exclude certain tables during snapshotting? I know I can list 50+ tables (except the ones I want to exclude) in `source.postgres.snapshot.tables`, but I'd prefer not to do that.
2. Is there an equivalent of the `PGSTREAM_POSTGRES_WRITER_SCHEMALOG_STORE_URL` variable for the .yaml config? It seems that pgstream ignores `PGSTREAM_*` variables when using `-c config.yaml`.

**Comment by gulcin** [comment]
Hello @skeggr thank you for your detailed feedback!

We're glad the initial issue you reported is now resolved! Regarding your questions:

> How can I exclude certain tables during snapshotting? I know I can list 50+ tables (except the ones I want to exclude) in source.postgres.snapshot.tables, but I'd prefer not to do that.

We've created #443 to support exclusion of tables during snapshotting.

> Is there an equivalent of the PGSTREAM_POSTGRES_WRITER_SCHEMALOG_STORE_URL variable for the .yaml config? It seems that pgstream ignores PGSTREAM_* variables when using -c config.yaml.

Yes, there is a YAML configuration equivalent for `PGSTREAM_POSTGRES_WRITER_SCHEMALOG_STORE_URL`. You can set this in your YAML config under the `target.postgres` section as follows:

```
target:
  postgres:
    url: "postgres://postgres:postgres@localhost:7654?sslmode=disable"
    batch:
      timeout: 5000
      size: 25
    schema_log_store_url: "postgres://postgres:postgres@localhost:5432?sslmode=disable"
    disable_triggers: false
    on_conflict_action: "nothing"
```
YAML configuration and environment (.env) configuration are not compatible and cannot be used together. You must choose either YAML or environment variables for configuration, using both at the same time is not supported.

**Comment by gulcin** [comment]
Hello @skeggr,

To address your second [comment](https://github.com/xataio/pgstream/issues/437#issuecomment-3083042519):

```
modifiers:
  filter: # one of include_tables or exclude_tables
    include_tables: # list of tables for which events should be allowed. Tables should be schema qualified. If no schema is provided, the public schema will be assumed. Wildcards "*" are supported.
      - "inventory.*"
    exclude_tables:
      - "inventory.transactions"
      - "inventory.products"
  ```
You cannot use both `include_tables` and `exclude_tables` at the same time. That said, you should have seen an error like:
`cannot use both include and exclude lists for table filtering`.

With #448, we’re fixing the issue so this error is properly raised when both are used.

Thanks again for catching this, we really appreciate your help!

**Comment by gulcin** [comment]
Hey @skeggr,

We've just published a bugfix [release](https://github.com/xataio/pgstream/releases/tag/v0.7.6) 🎉 

I wanted to keep you updated!

**Comment by gulcin** [comment]
Hi @skeggr , with the merge of #452, we've completed the work for [Snapshots: Add support for exclude tables filter](#443 )! Just wanted to keep you in the loop. 🚀
